[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "ndlbulkdownload"
readme = "README.md"
license = {text = "MIT"}
dynamic = ["version"]
requires-python = ">= 3.9"
dependencies = [
  "requests",
  "tqdm",
]
maintainers = [
  { name="Nasdaq Data Link Development Team", email="connect@data.nasdaq.com" },
]
description = "Data Link CLI Bulk Download Utility"
keywords = [
  'nasdaq data link',
  'nasdaq',
  'datalink',
  'console',
  'terminal',
  'cli',
  'data',
  'financial',
  'economic',
]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3 :: Only",
  "Topic :: Terminals",
  "Topic :: Utilities",
]

[project.scripts]
bulkdownload = "ndlbulkdownload.cli:main"

[project.urls]
Homepage = "https://github.com/nasdaq/ndlbulkdownload"
Issues = "https://github.com/nasdaq/ndlbulkdownload/issues"
Changelog = "https://github.com/nasdaq/ndlbulkdownload/blob/master/CHANGELOG.md"

[project.optional-dependencies]
lint = [
  "ruff",
  "pre-commit",
]
build = [
  "twine",
  "build",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/ndlbulkdownload/_version.py"

[tool.ruff.format]
indent-style = "space"

[tool.hatch.build.targets.sdist]
include = ["src"]
